---
- name: Demo Molecule playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Role Testing
      ansible.builtin.include_role:
        name: iamgini.moleculedemo.install_web
        tasks_from: main.yml