---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Test message for converge
      ansible.builtin.debug:
        msg: "Testing on {{ inventory_hostname }}"

    - name: "Include backup_file"
      ansible.builtin.include_role:
        name: iamgini.meetupdemo.web
