---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    # Developer must implement.

    # Mandatory configuration for Molecule to function.
    - name: Create
      block:
        - name: Destroy containers
          containers.podman.podman_container:
            name: "{{ item.name }}"
            image: "{{ item.image }}"
            state: absent
            command: sleep 1d
            # bash -c "while true; do sleep 10000; done"
            log_driver: json-file
          register: server
          loop: "{{ molecule_yml.platforms }}"

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
