---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
  options:
    managed: false
    login_cmd_template: "podman exec -it {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  # - name: instance
  - name: molecule-ubi8-init-1
    image: registry.access.redhat.com/ubi8/ubi-init
    workingDir: '/tmp'
  - name: molecule-ubi9-init-1
    image: registry.access.redhat.com/ubi9/ubi-init
  # - name: molecule-fedora-40
  #   image: fedora:40
  # - name: molecule-ubuntu
  #   image: ubuntu:latest
  - name: molecule-centos-stream8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  # Failing to write the ansible into /.ansible/tmp
  config_options:
    defaults:
      remote_tmp: '/tmp'
      # This just says go back a directory and thats your roles path
      # You can also provide this via pipeline with something like this
      # ANSIBLE_ROLES_PATH: $COLLECTION_ROLES

      # COLLECTIONS_PATH: ${PROJECT_SOURCE}
      # ANSIBLE_ROLES_PATH: ${PROJECT_SOURCE}/${backup_file_molecule_namespace}
  inventory:
    group_vars:
      all:
        backup_file_molecule_namespace: ${DEVWORKSPACE_NAMESPACE}
        backup_file_molecule_pip_dependencies:
          - kubernetes
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
